### ISSUE TITLE
[BUG] Armor Overlapping Nuka Cola Girl Rocket Suit

### ISSUE THREAD

**Issue by RaneScape** [bugthesda/Fallout76-Issue-Tracker#6]
![nuka](https://user-images.githubusercontent.com/47236432/52104060-8ac88100-259d-11e9-9a39-9b78377a5bf9.PNG)
With the most recent update Armor such as chameleon armor, raider armor etc. is over lapping the Nuka cola girl rocket suit. I don't think this is a new "feature" considering the belt of the armor is clipping through the belt of the cola suit. This also happens with the helmet/tank and the chest plate. As the Nuka Cola Girl Rocket Suit is an item purchased from the atom shop it was expected to overlap/hide all other armor (not power armor ik). If this is in fact a new change I'm unhappy with it, but I see no reason why it would be. When I first bought the suit this didn't happen for clarification.

 OS: Windows 10 64 bit
 Game Version: 1.0.5.14

**Comment by despotak** [comment]
I can confirm.

While `ATX_Clothes_NukaGirlOutfit "Nuka-Girl Rocketsuit" [ARMO:001135E5]` **correctly** does not have the flag `BOD2 - Biped Body Template -> First Person Flags -> 36 - [U] Torso`  (so that you can still wear something else in that spot), `DLC04_NukaSpaceOutfitBody [ARMA:001135C1]` **incorrectly** does not have the flag `BOD2 - Biped Body Template -> First Person Flags -> 41 - [A] Torso` .
![image](https://user-images.githubusercontent.com/8259004/52112322-cf403500-260e-11e9-81f3-f16b7cbf524f.png)

![image](https://user-images.githubusercontent.com/8259004/52112291-bd5e9200-260e-11e9-9e8e-9cd3934a5a7e.png)

**Comment by tesivo** [comment]
Now (with patch 6) it seems that the problem has been solved

**Comment by VhatAmI** [comment]
@RaneScape  can you confirm and close if fixed?

**Comment by despotak** [comment]
This was resolved with the `v1.0.6.0`

Confirmed as fixed.
![image](https://user-images.githubusercontent.com/8259004/53104723-92de6580-3538-11e9-8b03-c5210bb95444.png)
